baseURL = "https://alireza.es"
languageCode = "en-us"
title = "بلاگ علیرضا احمدی"
theme = "vivid"
shamsiDateFormat = "d MMM ماه yyyy"

paginate = 1000
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
ignoreFiles = ["\\.less$"]

[sitemap]
    priority = "0.5"
